# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: javafamily-central # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/.github # location for the settings.xml file

    - name: Publish to GitHub Packages Apache Maven
      run: mvn clean deploy -s $GITHUB_WORKSPACE/.github/settings.xml
